version: '3.3'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql
# Names our volume
volumes:
  database: